on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: e2e testing

jobs:
  test:
    name: e2e testing
    runs-on: ubuntu-latest

    env:
      OPENAI_APIKEY: {{ secrets.OPENAI_API_KEY }}

    defaults:
      run:
        shell: bash
        working-directory: e2e-examples

    steps:
      - uses: actions/checkout@v2

      - name: debug
        run: ls -a

      - name: Setup Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Setup Poetry 1.5.1
        run: pip install poetry==1.5.1

      - name: Check pyproject.toml
        run: poetry check

      - name: Install python dependencies with Poetry
        run: poetry install

      - name: Run tests
        run: poetry run pytest