on:
  release:
    types: [created]

jobs:
    gobuild:
        permissions: write-all
        name: Release Go Binary
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20.3.1
            registry-url: 'https://registry.npmjs.org/'
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: ^1.20.5
        - name: Install UPX
          run: | 
            curl -sfL https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz | tar -xJvf -;
            sudo mv upx-4.0.2-amd64_linux/upx /usr/local/bin;
            rm -rf upx-4.0.2-amd64_linux/
        - name: Test Go
          run: make test
        - name: Build Go
          run: make -C cli build
        - name: Release Go package
          run: make -C cli github-upload
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        - name: Publish NPM
          run: cd npm && make release
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}